commerce_payment.commerce_payment_gateway.plugin.paypal_user:
  type: commerce_payment_gateway_configuration
  mapping:
    api_user:
      type: string
      label: 'Username'
    api_pass:
      type: string
      label: 'Password'
    api_signature:
      type: string
      label: 'Signature'
